services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: GENERIC_TIMEZONE
        value: "Asia/Taipei"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
    autoDeploy: true
  - type: web
    name: n8n-translation-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
