services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: GENERIC_TIMEZONE
        value: "Asia/Taipei"
      - key: N8N_PORT
        value: "5678"
    autoDeploy: true
